### ISSUE TITLE
Asking a Permission

### ISSUE THREAD

**Issue by e-splat** [Starmute/terralith#2]
Hi, thank you if you are reading this message, I am creating a modpack to publish on Modrinth (SpongeVanilla for SpongeGames), but I learned that to use your Mods (Terralith and Incendium) I need your permission due to their license, do you grant me this permission? Sincerely.

**Comment by catter1** [comment]
Hi, please read our license. Here is the line that will pertain to you:
`- You are PERMITTED to use Stardust Labs datapacks or mods in their UNMODIFIED form as part of a publicly distributed modpack. If you do so, you MUST give credit to Starmute and include a link to the relevant datapack or mod. The datapack or mod must be used in its whole form (besides any compatibility addons for other datapacks.)`

You are allowed to use the mods in your modpacks without needing permission, as long as you provide credit somewhere, and use an unmodified version (the official version available for download from Curseforge or PMC or Seedfix).
